/** @type {import('prettier').Config} */
module.exports = {
  singleQuote: false,
  trailingComma: "none",
  printWidth: 100,
  plugins: ["@ianvs/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
  tailwindFunctions: ["cn", "clsx", "cva"],
  importOrder: [
    "^react$",
    "^next($|/)",
    "^@nextjs($|/)",
    "",
    "^@tanstack/.*",
    "^lucide-react($|/)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@repo/.*",
    "",
    "^@/types/.*",
    "^@/constants/.*",
    "^@/schemas($|/)",
    "^@/config/.*",
    "^@/env($|/)",
    "",
    "^@/assets/.*",
    "^@/styles/.*",
    "^@/lib/.*",
    "^@/helpers/.*",
    "^@/messages/.*",
    "",
    "^@/providers/.*",
    "^@/hooks($|/)",
    "^@/data($|/)",
    "",
    "^@/components($|/)",
    "^@/layouts($|/)",
    "^@/widgets($|/)",
    "^@/ui($|/)",
    "^@/.*",
    "",
    "^@/tailwind($|/)",
    "^[./]"
  ],
  importOrderParserPlugins: ["typescript", "jsx"]
};
